testing the git actions that it is testing second time

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -35,8 +35,12 @@ jobs:
     - name: Build with Maven
       run: mvn -B clean verify package --file pom.xml
 
-    - name: Run Tests
-      run: mvn surefire:test
+    - name: Check for test results
+      run: |
+        if grep -R --include=*.xml -E '<failure|<error' ./target/surefire-reports/; then
+          echo "Tests failed"
+          exit 1
+        fi
 
     # - name: Publish to GitHub Packages Apache Maven
     #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
